name: Publishing
on:
  push:
    branches: ["main"]

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v6

      - name: Setup Deno
        uses: denoland/setup-deno@2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install

      - name: Build client
        run: npm run build

      - name: Deploy jsr package
        run: npx jsr publish
        
